# Generated by Django 4.2.28 on 2026-03-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('replied', 'Replied'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('reply', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('TS', 'Telangana')], default='AP', max_length=5)),
                ('pincode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('google_maps_link', models.URLField(blank=True)),
                ('working_days', models.CharField(default='Monday to Saturday', max_length=100)),
                ('working_hours', models.CharField(default='8:00 AM - 7:00 PM', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_centers/')),
                ('manager_name', models.CharField(blank=True, max_length=100)),
                ('total_bays', models.IntegerField(default=10)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('payment_qr_code', models.ImageField(blank=True, help_text='Upload UPI QR code image for this service center', null=True, upload_to='payment_qr/')),
                ('upi_id', models.CharField(blank=True, default='smartrepair@upi', help_text='UPI ID e.g. smartrepair.vjw@upi', max_length=100)),
            ],
            options={
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('vehicle_type', models.CharField(choices=[('2w', 'Two Wheeler'), ('3w', 'Three Wheeler'), ('4w', 'Four Wheeler'), ('heavy', 'Heavy Vehicle'), ('all', 'All Vehicles')], default='all', max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_duration', models.IntegerField(help_text='Duration in hours')),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_national', models.BooleanField(default=False)),
                ('service_centers', models.ManyToManyField(blank=True, help_text='Leave empty for all centers', to='core.servicecenter')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
