# Generated by Django 4.2.28 on 2026-03-20 12:59

import bookings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(default=bookings.models.generate_booking_id, max_length=20, unique=True)),
                ('booking_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline/Walk-in')], default='online', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('problem_description', models.TextField(blank=True)),
                ('issue_notes', models.TextField(blank=True, help_text='Additional notes about the issues')),
                ('otp_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer_km_reading', models.IntegerField(blank=True, null=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('distance_from_center', models.FloatField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='accounts.employee')),
                ('assigned_workers', models.ManyToManyField(blank=True, related_name='worker_bookings', to='accounts.employee')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepairIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('engine', 'Engine'), ('brakes', 'Brakes & Suspension'), ('electrical', 'Electrical'), ('tyres', 'Tyres & Wheels'), ('ac', 'AC & Cooling'), ('body', 'Body & Paint'), ('transmission', 'Transmission & Clutch'), ('fuel', 'Fuel System'), ('service', 'Periodic Service'), ('other', 'Other')], default='other', max_length=30)),
                ('vehicle_type', models.CharField(choices=[('2w', 'Two Wheeler'), ('3w', 'Three Wheeler'), ('4w', 'Four Wheeler'), ('heavy', 'Heavy Vehicle'), ('all', 'All Vehicles')], default='all', max_length=10)),
                ('estimated_cost_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_cost_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['vehicle_type', 'category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_issues', models.ManyToManyField(blank=True, to='bookings.repairissue')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_assignments', to='bookings.booking')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_assignments', to='accounts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('2w', 'Two Wheeler'), ('3w', 'Three Wheeler'), ('4w', 'Four Wheeler'), ('heavy', 'Heavy Vehicle')], max_length=10)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('cng', 'CNG'), ('hybrid', 'Hybrid')], default='petrol', max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('chassis_number', models.CharField(blank=True, max_length=50)),
                ('engine_number', models.CharField(blank=True, max_length=50)),
                ('current_km', models.IntegerField(default=0)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_bookings', models.IntegerField(default=5)),
                ('current_bookings', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='core.servicecenter')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('service_center', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True)),
                ('work_done', models.TextField()),
                ('parts_replaced', models.TextField(blank=True)),
                ('next_service_km', models.IntegerField(blank=True, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('technician_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('km_reading', models.IntegerField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_record', to='bookings.booking')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='accounts.employee')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='RepairCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('selected', 'Customer Selected Issue'), ('diagnosed', 'Diagnosed at Center'), ('parts', 'Parts & Materials'), ('labour', 'Labour Charges'), ('extra', 'Extra / Additional Work'), ('service', 'Service Charge')], default='service', max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_extra', models.BooleanField(default=False, help_text='Extra work added after inspection')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_charges', to='bookings.booking')),
                ('repair_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.repairissue')),
            ],
            options={
                'ordering': ['charge_type', 'added_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_issues',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='bookings.repairissue'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicecenter'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_types',
            field=models.ManyToManyField(blank=True, to='core.servicetype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.timeslot'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.vehicle'),
        ),
    ]
